#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Folder }}'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

  [[blocks.segments]]
  type = 'path'
  style = 'plain'
  background = 'transparent'
  foreground = 'cyan'
  template = '{{ .Path }}'

    [blocks.segments.properties]
    style = 'full'

[[blocks]]
type = 'prompt'
alignment = 'right'

  [[blocks.segments]]
  type = 'git'
  style = 'plain'
  foreground = 'p:blue'
  background = 'transparent'
  foreground_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:blue{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:orange{{ end }}",
    "{{ if gt .Ahead 0 }}p:purple{{ end }}",
    "{{ if gt .Behind 0 }}p:purple{{ end }}",
  ]

  templates = [
    "{{ .HEAD }}",
    "{{ if .BranchStatus }}<p:cyan> {{ .BranchStatus }}</>{{ end }}",
    "{{ if .Working.Changed }}<p:pink>  {{ .Working.String }}</>{{ end }}",
    "{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}",
    "{{ if .Staging.Changed }}<p:orange>  {{ .Staging.String }}</>{{ end }}",
  ]

    [blocks.segments.properties]
    branch_icon = ''
    # commit_icon = '@'
    fetch_status = true
    # fetch_upstream_icon = true

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

  [[blocks.segments]]
  type = 'executiontime'
  style = 'plain'
  foreground = 'p:yellow'
  background = 'transparent'
  template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
    threshold = 5000

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:pink{{end}}",
  ]
  background = 'transparent'
  template = '❯'

[transient_prompt]
foreground_templates = [
  "{{if gt .Code 0}}p:red{{end}}",
  "{{if eq .Code 0}}p:pink{{end}}",
]
background = 'transparent'
template = '❯ '

[secondary_prompt]
foreground = 'p:orange'
background = 'transparent'
template = '❯❯ '

[palette]
# https://draculatheme.com/contribute#color-palette
black = "#282a36"  # Background
blue = "#6272a4"   # Comments
cyan = "#8be9fd"
green = "#50FA7B"
grey = "#44475A"   # Current Line
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#FF5555"
white = "#f8f8f2"  # Foreground
yellow = "#f1fa8c"
