console_title_template = '{{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#282a36'
  blue = '#6272a4'
  cyan = '#8be9fd'
  green = '#50FA7B'
  grey = '#44475A'
  orange = '#ffb86c'
  pink = '#ff79c6'
  purple = '#bd93f9'
  red = '#FF5555'
  white = '#f8f8f2'
  yellow = '#f1fa8c'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:orange'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:pink{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'cyan'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    foreground = 'p:blue'
    background = 'transparent'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:blue{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:orange{{ end }}', '{{ if gt .Ahead 0 }}p:purple{{ end }}', '{{ if gt .Behind 0 }}p:purple{{ end }}']
    templates = ['{{ .HEAD }}', '{{ if .BranchStatus }}<p:cyan> {{ .BranchStatus }}</>{{ end }}', '{{ if .Working.Changed }}<p:pink>  {{ .Working.String }}</>{{ end }}', '{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}', '{{ if .Staging.Changed }}<p:orange>  {{ .Staging.String }}</>{{ end }}']

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:pink{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
