#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
bundle exec ruby -rbundler/setup -e 'puts $LOAD_PATH.join(" ")' | xargs -J % find '%' -name '*.rb' | xargs -J % ctags --tag-relative -af"$dir/$$.tags" '%'
git ls-files | \
    ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-sql
mv "$dir/$$.tags" "$dir/tags"
