#!/bin/sh
rm -f .git/tags
bundle exec ruby -rbundler/setup -e 'puts $LOAD_PATH.join(" ")' | xargs -J % find '%' -name '*.rb' | xargs -J % ctags --tag-relative -af.git/tags '%'
ctags --tag-relative -Raf.git/tags app config features lib spec
